### PR TITLE
WAV-2690: Update the API description at https://docs.wavely.io/

### PR DESCRIPTION
**Pull request by lizozavr**

### CODE REVIEW

**Review by clissau — APPROVED** [review]
What is your opinion about "Gets" vs "Get"?
like: `Gets all SIM card locations of the company.`

**Comment by lizozavr** [comment]
> What is your opinion about "Gets" vs "Get"?
> like: `Gets all SIM card locations of the company.`

**Comment by lizozavr** [comment]
> What is your opinion about "Gets" vs "Get"?
> like: `Gets all SIM card locations of the company.`

I'd say 'Get' sounds more natural to me

**Comment by clissau** [comment]
> > What is your opinion about "Gets" vs "Get"?
> > like: `Gets all SIM card locations of the company.`
> 
> I'd say 'Get' sounds more natural to me

I agree.

**Review by clissau — APPROVED** [review]

**Review by haodengwavely — APPROVED** [review]

**Pull request merged**
